### ISSUE TITLE
Specifying a PBAE you have not scribed gives no error

### ISSUE THREAD

**Issue by martinlindhe** [cream24/Macros#5]
Minor head scratcher, but could be helpful if e3 warned if a PBAE specified in INI is not in the character's spell book.

**Comment by cream24** [comment]
when i test this i get a beep/warning and "...i do not have this spell|aa|ability|disc|item accessible"
PBAE=bla

**Comment by martinlindhe** [comment]
I do not mean specifying invalid spell name.

I mean specifying a valid spell name which is not in your spell book. Such is the result when you copy INI to a new toon.
