### ISSUE TITLE
Bot Buff argument order matters

### ISSUE THREAD

**Issue by martinlindhe** [cream24/Macros#7]
The following line works fine:

`Bot Buff=Voice of Quellious/Stor/Gem|8/MinMana|30`

While using this line, the buff is never cast:

`Bot Buff=Voice of Quellious/Gem|8/Stor/MinMana|30`

EDIT: using v7 as posted on peqtgc.com forums

**Comment by cream24** [comment]
yes the order matters for spell name and target, otherwise they would require a tag like /Target|Creamo.  see no value providing that ability
