### ISSUE TITLE
Summoned pets dont get /pet ghold on

### ISSUE THREAD

**Issue by martinlindhe** [cream24/Macros#8]
# The issue

When e3 is started or toon zones, an existing pet gets ordered "/pet ghold on" once in https://github.com/cream24/Macros/blob/master/e3%20Includes/e3_Background.inc#L16

While e3 is running a long time in a zone and the pet toon dies, the newly summoned pet will not be told "/pet ghold on".

# The fix

in https://github.com/cream24/Macros/blob/master/e3%20Includes/e3_Pets.inc#L21

add this to end of summonPets function:

```
  /if (${Me.Pet.ID}) {
    /squelch /pet ghold on
  }
```

**Comment by cream24** [comment]
added
